# -*- coding: utf-8 -*-
"""Lab7_SPR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqLNEu9IZw5GcD5qj9qDorYNx69W0Vf6
"""

# ---------------------------------------------------------------
# Lab Question 7: Dynamic Time Warping on "hello" audio signals
# ---------------------------------------------------------------

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Step 1: Load audio recordings
# -----------------------------
file1 = "/content/female_hello_how_are_you.wav"
file2 = "/content/male_hello_how_are_you.wav"

sig1, sr1 = librosa.load(file1, sr=16000)
sig2, sr2 = librosa.load(file2, sr=16000)

# -----------------------------
# Step 2: Normalize amplitudes
# -----------------------------
sig1 = sig1 / np.max(np.abs(sig1))
sig2 = sig2 / np.max(np.abs(sig2))

# -----------------------------
# Step 3: Trim silence (optional but clean)
# -----------------------------
sig1, _ = librosa.effects.trim(sig1, top_db=30)
sig2, _ = librosa.effects.trim(sig2, top_db=30)

# -----------------------------
# Step 4: Convert to MFCC
# -----------------------------
mfcc1 = librosa.feature.mfcc(y=sig1, sr=16000, n_mfcc=20)
mfcc2 = librosa.feature.mfcc(y=sig2, sr=16000, n_mfcc=20)

# -----------------------------
# Step 5: Apply DTW
# -----------------------------
D, wp = librosa.sequence.dtw(mfcc1, mfcc2, metric="euclidean")
wp = np.array(wp)[::-1]

dtw_distance = D[-1, -1]
print("DTW Distance:", dtw_distance)



plt.figure(figsize=(10,5))
librosa.display.specshow(mfcc1, sr=16000, x_axis='time', cmap='magma')
plt.title("MFCC Heatmap: Your Voice (Magma Theme)")
plt.colorbar()
plt.show()

plt.figure(figsize=(10,5))
librosa.display.specshow(mfcc2, sr=16000, x_axis='time', cmap='viridis')
plt.title("MFCC Heatmap: Friend Voice (Viridis Theme)")
plt.colorbar()
plt.show()

plt.figure(figsize=(8,6))

plt.imshow(D, origin='lower', cmap='cubehelix', aspect='auto')
plt.plot(wp[:,1], wp[:,0], color='yellow', linewidth=2)

plt.title("Optimal Warping Path over Cost Matrix")
plt.xlabel("Signal 2 Index")
plt.ylabel("Signal 1 Index")
plt.colorbar()
plt.show()

plt.figure(figsize=(10,5))

plt.plot(sig1, label="Signal 1", color='cyan')
plt.plot(sig2, label="Signal 2", color='magenta', alpha=0.7)

# Draw alignment lines every few points
step = len(wp)//50
for i in range(0, len(wp), step):
    i1, i2 = wp[i]
    plt.plot([i1, i2], [sig1[i1], sig2[i2]], color='white', alpha=0.3)

plt.title("DTW Alignment Connections (Spaghetti Plot)")
plt.legend()
plt.grid(True)
plt.show()

local_cost = np.sum((mfcc1[:, :min(mfcc1.shape[1], mfcc2.shape[1])] -
                     mfcc2[:, :min(mfcc1.shape[1], mfcc2.shape[1])])**2, axis=0)

plt.figure(figsize=(10,4))
plt.plot(local_cost, color='orange')
plt.title("Local Distance Curve Between the Two Voices")
plt.xlabel("Frame Index")
plt.ylabel("Distance")
plt.grid(True)
plt.show()