# -*- coding: utf-8 -*-
"""SPR_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gQ70LgnwVk-U2x01gW1t7MrfkKsliTn
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
fs = 1000  # Sampling frequency
T = 1.0    # Duration in seconds
t = np.arange(0, T, 1/fs)
N = len(t)

# Helper functions
def compute_dft(x):
    X = np.fft.fft(x)
    freqs = np.fft.fftfreq(len(x), d=1/fs)
    return np.fft.fftshift(X), np.fft.fftshift(freqs)

def compute_dtft_approx(x, nfft=16384):
    X = np.fft.fft(x, n=nfft)
    freqs = np.fft.fftfreq(nfft, d=1/fs)
    return np.fft.fftshift(X), np.fft.fftshift(freqs)

# ---------- Q1: Single sinusoid ----------
f1 = 5
x1 = np.sin(2*np.pi*f1*t)

plt.figure(figsize=(10,3))
plt.plot(t, x1)
plt.title("Q1: Sinusoidal Signal (5 Hz)")
plt.xlabel("Time (s)"); plt.ylabel("Amplitude")
plt.xlim(0, 0.4)
plt.show()

# DTFT approx
X1_dtft, freqs_dtft = compute_dtft_approx(x1)
plt.figure(figsize=(10,3))
plt.plot(freqs_dtft, np.abs(X1_dtft))
plt.title("Q1: DTFT (approx)")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(-50,50)
plt.show()

# DFT
X1_dft, freqs_dft = compute_dft(x1)
plt.figure(figsize=(10,3))
plt.stem(freqs_dft, np.abs(X1_dft), basefmt=" ")
plt.title("Q1: DFT")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(-50,50)
plt.show()

# ---------- Q2: Composite signal ----------
f2a, A2a = 50, 1.0
f2b, A2b = 120, 0.6
x2 = A2a*np.sin(2*np.pi*f2a*t) + A2b*np.sin(2*np.pi*f2b*t + 0.4)

plt.figure(figsize=(10,3))
plt.plot(t, x2)
plt.title("Q2: Composite Signal (50 Hz + 120 Hz)")
plt.xlabel("Time (s)"); plt.ylabel("Amplitude")
plt.xlim(0, 0.05)
plt.show()

# DTFT approx
X2_dtft, freqs_dtft = compute_dtft_approx(x2, nfft=32768)
plt.figure(figsize=(10,3))
plt.plot(freqs_dtft, np.abs(X2_dtft))
plt.title("Q2: DTFT (approx)")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(0,200)
plt.show()

# DFT
X2_dft, freqs_dft = compute_dft(x2)
plt.figure(figsize=(10,3))
plt.stem(freqs_dft, np.abs(X2_dft), basefmt=" ")
plt.title("Q2: DFT")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(0,200)
plt.show()

# ---------- Q3: Exponentially decaying signal ----------
alpha = 0.98
x3 = alpha**np.arange(N)

plt.figure(figsize=(10,3))
plt.plot(t, x3)
plt.title("Q3: Exponentially Decaying Signal")
plt.xlabel("Time (s)"); plt.ylabel("Amplitude")
plt.show()

# DTFT approx
X3_dtft, freqs_dtft = compute_dtft_approx(x3)
plt.figure(figsize=(10,3))
plt.plot(freqs_dtft, np.abs(X3_dtft))
plt.title("Q3: DTFT (approx)")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(-200,200)
plt.show()

# DFT
X3_dft, freqs_dft = compute_dft(x3)
plt.figure(figsize=(10,3))
plt.stem(freqs_dft, np.abs(X3_dft), basefmt=" ")
plt.title("Q3: DFT")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(-200,200)
plt.show()

# ---------- Q4: Rectangular pulse ----------
pulse_width_sec = 0.05
pulse_width_samples = int(pulse_width_sec*fs)
x4 = np.zeros_like(t)
start = int(0.2*fs)
x4[start:start+pulse_width_samples] = 1

plt.figure(figsize=(10,3))
plt.plot(t, x4)
plt.title("Q4: Rectangular Pulse")
plt.xlabel("Time (s)"); plt.ylabel("Amplitude")
plt.xlim(0.15,0.3)
plt.show()

# DTFT approx
X4_dtft, freqs_dtft = compute_dtft_approx(x4, nfft=32768)
plt.figure(figsize=(10,3))
plt.plot(freqs_dtft, np.abs(X4_dtft))
plt.title("Q4: DTFT (approx)")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(0,2000)
plt.show()

# DFT
X4_dft, freqs_dft = compute_dft(x4)
plt.figure(figsize=(10,3))
plt.stem(freqs_dft, np.abs(X4_dft), basefmt=" ")
plt.title("Q4: DFT")
plt.xlabel("Frequency (Hz)"); plt.ylabel("Magnitude")
plt.xlim(0,2000)
plt.show()



