# -*- coding: utf-8 -*-
"""SPR_lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10F1i6FDaGf9kAANKNNrRTUEvigY6O1-n
"""

import numpy as np
import matplotlib.pyplot as plt

# States and observations
states = ['h', 'e', 'l', 'o']
observations = ['O1', 'O2', 'O3', 'O4']

# Transition Probability Matrix A
A = np.array([
    [0.6, 0.3, 0.1, 0.0],   # h -> h,e,l,o
    [0.0, 0.6, 0.3, 0.1],   # e -> h,e,l,o
    [0.0, 0.0, 0.7, 0.3],   # l -> h,e,l,o
    [0.0, 0.0, 0.0, 1.0]    # o -> h,e,l,o (absorbing)
])

# Emission Probability Matrix B
B = np.array([
    [0.9, 0.1, 0.0, 0.0],   # h emits O1,O2,O3,O4
    [0.0, 0.8, 0.2, 0.0],
    [0.0, 0.0, 0.9, 0.1],
    [0.0, 0.0, 0.0, 1.0]
])

# Initial probabilities
pi = np.array([1.0, 0.0, 0.0, 0.0])

# Observation sequence indices
O = [0, 1, 2, 3]  # O1 O2 O3 O4

def viterbi(pi, A, B, O):
    T = len(O)
    N = len(pi)

    delta = np.zeros((T, N))
    psi = np.zeros((T, N), dtype=int)

    delta[0] = pi * B[:, O[0]]

    for t in range(1, T):
        for j in range(N):
            transition_probs = delta[t - 1] * A[:, j]
            psi[t][j] = np.argmax(transition_probs)
            delta[t][j] = np.max(transition_probs) * B[j][O[t]]

    last_state = np.argmax(delta[T - 1])
    best_path_prob = np.max(delta[T - 1])

    best_path = [last_state]
    for t in range(T - 1, 0, -1):
        best_path.insert(0, psi[t][best_path[0]])

    return best_path, best_path_prob, delta, psi

best_path, best_prob, delta, psi = viterbi(pi, A, B, O)

decoded_states = [states[i] for i in best_path]
print("Most likely phoneme sequence:", decoded_states)
print("Probability of best sequence:", best_prob)

plt.figure(figsize=(6,4))
plt.plot(best_path, marker="o")
plt.yticks([0,1,2,3], states)
plt.xlabel("Time step")
plt.ylabel("State")
plt.title("Viterbi Decoded State Path for 'hello'")
plt.grid()
plt.show()

import seaborn as sns

plt.figure(figsize=(7,4))
sns.heatmap(delta, annot=True, cmap="Blues")
plt.title("Delta Matrix Heatmap (Viterbi Probabilities)")
plt.xlabel("States")
plt.ylabel("Time steps")
plt.xticks([0.5,1.5,2.5,3.5], states)
plt.show()

plt.figure(figsize=(7,4))

for t in range(len(O)):
    plt.scatter([t]*4, range(4), s=200)

for t in range(1, len(O)):
    for s_prev in range(4):
        for s_curr in range(4):
            plt.plot([t-1, t], [s_prev, s_curr], color="gray", linewidth=0.5)

plt.plot(range(len(best_path)), best_path, color="red", linewidth=3, marker="o", label="Viterbi Best Path")

plt.yticks([0,1,2,3], states)
plt.xlabel("Time")
plt.ylabel("States")
plt.title("Trellis Diagram with Best Path Highlighted")
plt.legend()
plt.grid()
plt.show()