# -*- coding: utf-8 -*-
"""SPR_ lab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148JCuzQifnBwQq4yM-vRsgGGnFbYbp_q
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import networkx as nx

states = ['/s/', '/p/', '/ie:/', '/tS/']
observations = ['Energy', 'Pitch', 'Duration']

initial = {'/s/': 1, '/p/': 0, '/ie:/': 0, '/tS/': 0}

transition = {
    '/s/':  {'/s/':0, '/p/':1, '/ie:/':0, '/tS/':0},
    '/p/':  {'/s/':0, '/p/':0, '/ie:/':1, '/tS/':0},
    '/ie:/':{'/s/':0, '/p/':0, '/ie:/':0, '/tS/':1},
    '/tS/': {'/s/':0, '/p/':0, '/ie:/':0, '/tS/':1},
}

emission = {
    '/s/':   {'Energy':0.7, 'Pitch':0.2, 'Duration':0.1},
    '/p/':   {'Energy':0.5, 'Pitch':0.3, 'Duration':0.2},
    '/ie:/': {'Energy':0.3, 'Pitch':0.5, 'Duration':0.2},
    '/tS/':  {'Energy':0.4, 'Pitch':0.4, 'Duration':0.2}
}

# ---------------------------------------------------------
# Generate Sequence
# ---------------------------------------------------------

def generate():
    seq_states = ['/s/']
    seq_obs = []

    current = '/s/'

    for _ in range(3):
        obs = random.choices(list(emission[current]), weights=list(emission[current].values()))[0]
        seq_obs.append(obs)

        next_state = random.choices(list(transition[current]), weights=list(transition[current].values()))[0]
        seq_states.append(next_state)
        current = next_state

    return seq_states, seq_obs

phonemes, obs_values = generate()

print("Phonemes:", phonemes)
print("Observations:", obs_values)

# ---------------------------------------------------------
# Visualization 1: Heatmap for Transition Matrix
# ---------------------------------------------------------
plt.figure(figsize=(6,5))
sns.heatmap(
    np.array([[transition[s][t] for t in states] for s in states]),
    annot=True, cmap="Blues", xticklabels=states, yticklabels=states
)
plt.title("Transition Matrix")
plt.show()

# ---------------------------------------------------------
# Visualization 2: Heatmap for Emission Matrix
# ---------------------------------------------------------
plt.figure(figsize=(6,5))
sns.heatmap(
    np.array([[emission[s][o] for o in observations] for s in states]),
    annot=True, cmap="Greens", xticklabels=observations, yticklabels=states
)
plt.title("Emission Matrix")
plt.show()

# ---------------------------------------------------------
# Visualization 3: Timeline Style Plot
# ---------------------------------------------------------
plt.figure(figsize=(10,2))
plt.plot(range(len(phonemes)), phonemes, marker='o', color='red')
plt.title("Phoneme Timeline")
plt.yticks(fontsize=12)
plt.grid(True)
plt.show()

plt.figure(figsize=(10,2))
plt.plot(range(len(obs_values)), obs_values, marker='s', color='purple')
plt.title("Observation Timeline")
plt.yticks(fontsize=12)
plt.grid(True)
plt.show()

# ---------------------------------------------------------
# Visualization 4: Phoneme to Observation Flow
# ---------------------------------------------------------
plt.figure(figsize=(8,4))
for i in range(len(obs_values)):
    plt.plot([i, i], [0.2, 1], color='black')
    plt.scatter(i, 1, color='red', s=200)
    plt.scatter(i, 0.2, color='green', s=200)
    plt.text(i, 1.05, phonemes[i], ha='center')
    plt.text(i, 0.1, obs_values[i], ha='center')

plt.title("State to Observation Flow")
plt.xticks([])
plt.yticks([])
plt.show()


# ===========================================================
# 5. Bubble Plot for Emission Probabilities
# ===========================================================

plt.figure(figsize=(7,5))

for i, s in enumerate(states):
    for j, o in enumerate(observations):
        plt.scatter(i, j, s=emission[s][o] * 2000, color="green", alpha=0.6)

plt.xticks(range(len(states)), states)
plt.yticks(range(len(observations)), observations)
plt.title("Bubble Plot of Emission Strength")
plt.grid(True)
plt.show()


# ===========================================================
# 2. Bar Chart for Emissions
# ===========================================================

plt.figure(figsize=(8,4))
x = np.arange(len(states))

for i, obs in enumerate(observations):
    plt.bar(x + i*0.25, [emission[s][obs] for s in states], width=0.25, label=obs)

plt.xticks(x + 0.25, states)
plt.title("Emission Bar Chart")
plt.xlabel("Phoneme")
plt.ylabel("Probability")
plt.legend()
plt.show()