# -*- coding: utf-8 -*-
"""SPR_Lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-8xbl9pcDjjBz1puru4rZAEaCo5k5Xs
"""

# ==============================================
# Lab Exercise V – Linear Time Normalization (LTN)
# Aim: Align two speech signals using LTN
# ==============================================

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

# -------------------------------
# Step 1: Given Speech Signals
# -------------------------------
s1 = np.array([0.2, 0.4, 0.6, 0.8, 1.0, 0.8, 0.6, 0.4, 0.2])   # Reference (faster)
s2 = np.array([0.2, 0.3, 0.5, 0.7, 0.9, 1.0, 0.9, 0.7, 0.5, 0.4, 0.3, 0.2])  # Slower

# -------------------------------
# Step 2: Plot both signals
# -------------------------------
plt.figure(figsize=(8,4))
plt.plot(s1, 'o-', label='Signal 1 (Reference)')
plt.plot(s2, 's-', label='Signal 2 (Test)')
plt.title("Original Speech Signals")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.show()

# -------------------------------
# Step 3: Linear Time Normalization
# Make Signal 2 same length as Signal 1
# -------------------------------
x_old = np.linspace(0, 1, len(s2))
x_new = np.linspace(0, 1, len(s1))

interpolator = interp1d(x_old, s2)
s2_norm = interpolator(x_new)

# -------------------------------
# Step 4: Plot normalized Signal 2
# -------------------------------
plt.figure(figsize=(8,4))
plt.plot(s1, 'o-', label='Signal 1')
plt.plot(s2_norm, 'x--', label='Signal 2 Normalized (LTN)')
plt.title("Signal 2 After Linear Time Normalization")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.show()

# -------------------------------
# Step 5: Alignment Mapping Plot
# -------------------------------
plt.figure(figsize=(6,6))
for i in range(len(s1)):
    plt.plot([i, i], [s1[i], s2_norm[i]], 'r-')  # alignment lines

plt.plot(s1, 'bo-', label='Signal 1')
plt.plot(s2_norm, 'go--', label='Signal 2 Normalized')
plt.title("Alignment Path after LTN")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.show()